Lab/Assignment_1/config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  get '/books/:id/delete', to: 'books#delete', as: 'delete_book'
  resources :books
end

Lab/Assignment_1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Lab/Assignment_1/app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :genre, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0}
    validates :published_date, presence: true
end

Lab/Assignment_1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Lab/Assignment_1/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    #if true
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to root_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :genre, :price, :published_date)
    end
end

Lab/Assignment_1/app/helpers/application_helper.rb
module ApplicationHelper
end

Lab/Assignment_1/app/helpers/books_helper.rb
module BooksHelper
end

Lab/Assignment_1/app/helpers/home_helper.rb
module HomeHelper
end

Lab/Assignment_1/app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
    <% book.errors.full_messages_for(:author).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :genre %><br>
    <%= form.select :genre, [ 'Action & Adventure','Biography','Classic','Comic Book/Graphic Novel','Fantasy','Fiction','History','Horror','Mystery','Poetry','Romance','Science Fiction','Suspense/Thriller'], :prompt => 'Select One'%>
    <% book.errors.full_messages_for(:genre).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
    <% book.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :published_date %><br>
    <%= form.date_field :published_date %>
    <% book.errors.full_messages_for(:published_date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Lab/Assignment_1/app/views/books/delete.html.erb
<h1>Delete <%=@book.title %> </h1> 

<h3>Are you sure you want to delete <%= @book.title %>?</h3> 

<%= link_to "Delete Book", book_path(@book), method: :delete %> 

<br>

<%= link_to "Cancel", book_path(@book) %>

Lab/Assignment_1/app/views/books/edit.html.erb
<h1> Update <%=@book.title %> </h1>

<%= link_to "Home", root_path %>

<br>

<%= link_to "New Book", new_book_path %>

<br>

<%= link_to "Delete", delete_book_path(@book) %>

<%= render "form", book: @book %>

Lab/Assignment_1/app/views/books/index.html.erb
<h1>Book Collection</h1>

<%= link_to "New Book", new_book_path %>

<br>
<br>

<span style="width:150px; display:inline-block; font-weight:bold; text-decoration:underline">Title</span>
<span style="width:150px; display:inline-block; font-weight:bold; text-decoration:underline">Author</span>
<span style="width:150px; display:inline-block; font-weight:bold; text-decoration:underline">Genre</span>
<span style="width:150px; display:inline-block; font-weight:bold; text-decoration:underline">Price</span>
<span style="width:150px; display:inline-block; font-weight:bold; text-decoration:underline">Published Date</span>

<br>

<% @books.each do |book| %>
  <span style="width:150px; display:inline-block;"><%= book.title %></span>
  <span style="width:150px; display:inline-block;"><%= book.author %></span>
  <span style="width:150px; display:inline-block;"><%= book.genre %></span>
  <span style="width:150px; display:inline-block;"><%= number_to_currency(book.price) %></span>
  <span style="width:150px; display:inline-block;"><%= book.published_date.strftime("%m %d %Y") %></span>
  <%= link_to "Show", book %>
  <%= link_to "Update", edit_book_path(book) %>
  <%= link_to "Delete", delete_book_path(book) %> 
<% end %>

<br>

Lab/Assignment_1/app/views/books/new.html.erb
<h1>Add Book</h1>

<%= link_to "Home", root_path %>

<br>

<%= render "form", book: @book %>

Lab/Assignment_1/app/views/books/show.html.erb
<h1><%= @book.title %> Details</h1>

<%= link_to "Home", root_path %>

<br>

<%= link_to "Update", edit_book_path(@book) %>

<br>

<%= link_to "Delete", delete_book_path(@book) %>

<br>

<%= link_to "New Book", new_book_path %>

<br>

<p>Title: <%= @book.title %> </p>

<p>Author: <%= @book.author %></p>

<p>Genre: <%= @book.genre %></p>

<p>Price: <%= number_to_currency(@book.price) %></p>

<p>Published Date: <%= @book.published_date %></p>

Lab/Assignment_1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSCE431Assignment1Rhrussell</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>